version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5432:5432
      - 5672:5672
      - 15672:15672
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
      - POSTGRES_DB=voodoo-db

  kafka:
    image: landoop/fast-data-dev
    ports:
      - 3030:3030
      - 2181:2181
      - 9092:9092
      - 9093:9093
      - 8082:8081
    environment:
      ADV_HOST: localhost
