server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/areano/spring-cloud-config-repo
          refresh-rate: 5
          clone-on-start: true
          basedir: ${user.home}/temp/config-repo
          force-pull: true

  kafka:
    bootstrap-servers: localhost:9092

app:
  config:
    server:
      monitor:
        fixedDelay: 60000